
CREATE TABLE client (
    ID BIGSERIAL PRIMARY KEY,
    NAME VARCHAR(200) NOT NULL CHECK (LENGTH (NAME) > 3)
);
CREATE TABLE planet (
    ID VARCHAR(200) NOT NULL CHECK (ID ~ '^[A-Z]+$' AND LENGTH(ID) > 1) UNIQUE,
    NAME VARCHAR(500) NOT NULL CHECK (LENGTH (NAME) > 0) UNIQUE
);
CREATE TABLE ticket (
    ID BIGSERIAL PRIMARY KEY,
    CREATED_AT TIMESTAMP,
    CLIENT_ID BIGINT,
    FROM_PLANET_ID VARCHAR,
    TO_PLANET_ID VARCHAR,

        FOREIGN KEY (FROM_PLANET_ID) REFERENCES planet(ID),

        FOREIGN KEY (TO_PLANET_ID) REFERENCES planet(ID),

        FOREIGN KEY (CLIENT_ID) REFERENCES client(ID)
);